merge create cilium/cns with update cilium/cns, fix dualstack image tag, throw errors in pipeline stages

diff --git a/.pipelines/cni/cilium/cilium-scale-test.yaml b/.pipelines/cni/cilium/cilium-scale-test.yaml
--- a/.pipelines/cni/cilium/cilium-scale-test.yaml
+++ b/.pipelines/cni/cilium/cilium-scale-test.yaml
@@ -20,11 +20,31 @@ stages:
                 az extension add --name aks-preview
 
                 subscriptionId="$(az account list --query "[?isDefault].id" --output tsv)"
-                make -C ./hack/aks AZCLI=az ${CLUSTER_TYPE} CLUSTER=${CLUSTER} GROUP=${RESOURCE_GROUP} REGION=${LOCATION} NODE_COUNT=5 VM_SIZE=${VMSIZE} SUB=${subscriptionId}
+                make -C ./hack/aks AZCLI=az ${CLUSTER_TYPE} CLUSTER=${CLUSTER} GROUP=${RESOURCE_GROUP} REGION=${LOCATION} NODE_COUNT=5 VM_SIZE=${VMSIZE} SUB=${subscriptionId} || {
+                  echo "Failed to create Cluster"
+                  exit 1
+                }
                 ls -lah
                 pwd
                 kubectl cluster-info
                 kubectl get po -owide -A
+  - stage: update_daemonset_versions
+    displayName: "Update Cilium + CNS Version and Restart Nodes"
+    jobs:
+      - job: update_version
+        pool:
+          name: "$(BUILD_POOL_NAME_DEFAULT)"
+        steps:
+          - task: AzureCLI@2
+            inputs:
+              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
+              scriptLocation: "inlineScript"
+              scriptType: "bash"
+              addSpnToEnvironment: true
+              inlineScript: |
+                az aks get-credentials --resource-group ${RESOURCE_GROUP} --name ${CLUSTER}
+                echo "Redeploy all cilium components and update cilium version. Redeploy all to catch all changes between versions"
+                pwd
 
                 echo "install Cilium ${CILIUM_VERSION_TAG}"
                 export DIR=${CILIUM_VERSION_TAG%.*}
@@ -42,9 +62,10 @@ stages:
                 kubectl apply -f test/integration/manifests/cilium/v${DIR}/cilium-agent/files
                 kubectl apply -f test/integration/manifests/cilium/v${DIR}/cilium-operator/files
 
+                export CILIUM_VERSION_TAG=${CILIUM_VERSION_TAG}
+                export CILIUM_IMAGE_REGISTRY=${CILIUM_IMAGE_REGISTRY}
                 if ${IS_DUALSTACK}; then
                   echo "Use dualstack daemonset for Cilium"
-                  export IPV6_HP_BPF_VERSION=$(make ipv6-hp-bpf-version)
                   envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY},${IPV6_HP_BPF_VERSION}' < test/integration/manifests/cilium/v${DIR}/cilium-agent/templates/daemonset-dualstack.yaml | kubectl apply -f -
                 else
                   envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/v${DIR}/cilium-agent/templates/daemonset.yaml | kubectl apply -f -
@@ -56,42 +77,19 @@ stages:
                 echo "Deploy Azure-CNS"
                 sudo -E env "PATH=$PATH" make test-load AZURE_IPAM_VERSION=v$(AZURE_IPAM_VERSION) CNS_ONLY=true CNS_VERSION=v$(CNS_VERSION) INSTALL_CNS=true INSTALL_OVERLAY=true CNS_IMAGE_REPO=$(CNS_IMAGE_REPO)
                 kubectl get po -owide -A
-
-                kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=10m
+                kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=10m || {
+                  echo "Not all pods ready"
+                  kubectl get po -owide -A
+                  exit 1
+                }
                 kubectl get po -owide -A
-  - stage: update_daemonset_versions
-    condition: not(succeededOrFailed())
-    displayName: "Update Cilium + CNS Version and Restart Nodes"
-    jobs:
-      - job: update_version
-        pool:
-          name: "$(BUILD_POOL_NAME_DEFAULT)"
-        steps:
-          - task: AzureCLI@2
-            inputs:
-              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
-              scriptLocation: "inlineScript"
-              scriptType: "bash"
-              addSpnToEnvironment: true
-              inlineScript: |
-                az aks get-credentials --resource-group ${RESOURCE_GROUP} --name ${CLUSTER}
-                echo "Redeploy all cilium components and update cilium version. Redeploy all to catch all changes between versions"
-                echo "deploy Cilium ConfigMap"
-                kubectl apply -f test/integration/manifests/cilium/cilium-config.yaml
-                echo "install Cilium ${CILIUM_VERSION_TAG}"
-                envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/daemonset.yaml | kubectl apply -f -
-                envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/deployment.yaml | kubectl apply -f -
-                kubectl apply -f test/integration/manifests/cilium/cilium-agent
-                kubectl apply -f test/integration/manifests/cilium/cilium-operator
-                echo "Keep CNS version up to date, grabbing pipeline parameter"
-                CNS_IMAGE=${CNS_IMAGE}
-                sed -i '/containers:/{n;n;s/\(image\).*/\1: '"${CNS_IMAGE//\//\\/}"'/}' test/integration/manifests/cns/daemonset.yaml
-                kubectl apply -f test/integration/manifests/cns/daemonset.yaml
+
+                echo "Restart Nodes"
                 for val in $(az vmss list -g MC_${clusterName}_${clusterName}_$(REGION_AKS_CLUSTER_TEST) --query "[].name" -o tsv); do
                   make -C ./hack/aks restart-vmss AZCLI=az CLUSTER=${clusterName} REGION=$(REGION_AKS_CLUSTER_TEST) VMSS_NAME=${val}
                 done
                 kubectl get node
-                kubectl get pod -A
+                kubectl get po -owide -A
             name: "UpdateCiliumandCNSVersion"
             displayName: "Update Cilium and CNS Version"
   - stage: scale_up_cluster
