fixup! Add Agent Details

diff --git a/.pipelines/tools/install-tooling.steps.yaml b/.pipelines/tools/install-tooling.steps.yaml
--- a/.pipelines/tools/install-tooling.steps.yaml
+++ b/.pipelines/tools/install-tooling.steps.yaml
@@ -162,30 +162,30 @@ steps: #
             printVersion: true
             versionCmd: 'podman version'
             afterInstall:
-            - bash: |
-                set -e
-                ls -l /usr/share/containers/
-                #sudo ls -l /etc/containers || echo "No folder named /etc/containers"
-                BUILD_USER="$(whoami)"
-                sudo groupadd podman
-                usermod -aG podman "$BUILD_USER"
-                #mkdir -p /home/"$BUILD_USER" /home/"$BUILD_USER"/.config/containers -p /home/"$BUILD_USER"/.local/share/containers
-                #usermod -d /home/"$BUILD_USER" "$BUILD_USER"
-                echo podman:10000:5000 > /etc/subuid
-                echo podman:10000:5000 > /etc/subgid
-                #echo -e "$BUILD_USER:1:999\n$BUILD_USER:1001:124535" > /etc/subuid
-                #echo -e "$BUILD_USER:1:999\n$BUILD_USER:1001:124535" > /etc/subgid
-                #
-                #echo "${BUILD_USER}:x:$BUILD_USER_ID:0:${BUILD_USER} user:/home/$BUILD_USER:/bin/bash" >> /etc/passwd
-                #echo "${BUILD_USER}:x:$BUILD_USER_ID:" >> /etc/group
-                #chmod 644 /etc/containers/containers.conf && \
-                #chmod 644 /etc/containers/storage.conf || echo "unable to update permissions."
-
-                setcap cap_setuid+ep /usr/bin/newuidmap
-                setcap cap_setgid+ep /usr/bin/newgidmap
-                #chmod 555 /etc/passwd /etc/group /etc/subuid /etc/subgid /usr/bin/newgidmap
-                podman system migrate
-              displayName: "Set up Build User Permissions for Podman"
+            - template: podman.post-install.steps.yaml
+            #- bash: |
+                #set -e
+                #ls -l /usr/share/containers/
+                ##sudo ls -l /etc/containers || echo "No folder named /etc/containers"
+                #BUILD_USER="$(whoami)"
+                #sudo groupadd podman
+                #usermod -aG podman "$BUILD_USER"
+                ##mkdir -p /home/"$BUILD_USER" /home/"$BUILD_USER"/.config/containers -p /home/"$BUILD_USER"/.local/share/containers
+                ##usermod -d /home/"$BUILD_USER" "$BUILD_USER"
+                #echo podman:10000:5000 > /etc/subuid
+                #echo podman:10000:5000 > /etc/subgid
+                ##echo -e "$BUILD_USER:1:999\n$BUILD_USER:1001:124535" > /etc/subuid
+                ##echo -e "$BUILD_USER:1:999\n$BUILD_USER:1001:124535" > /etc/subgid
+                ##
+                ##echo "${BUILD_USER}:x:$BUILD_USER_ID:0:${BUILD_USER} user:/home/$BUILD_USER:/bin/bash" >> /etc/passwd
+                ##echo "${BUILD_USER}:x:$BUILD_USER_ID:" >> /etc/group
+                ##chmod 644 /etc/containers/containers.conf && \
+                ##chmod 644 /etc/containers/storage.conf || echo "unable to update permissions."
+                #setcap cap_setuid+ep /usr/bin/newuidmap
+                #setcap cap_setgid+ep /usr/bin/newgidmap
+                ##chmod 555 /etc/passwd /etc/group /etc/subuid /etc/subgid /usr/bin/newgidmap
+                #podman system migrate
+              #displayName: "Set up Build User Permissions for Podman"
 
           ${{ elseif eq(tool, 'skopeo') }}:
             installCmd: 'skopeo' # Add the pkg name & parameters - pkgmgr will be determined by template
