fixup! Add Agent Details

diff --git a/.pipelines/tools/podman.post-install.steps.yaml b/.pipelines/tools/podman.post-install.steps.yaml
--- a/.pipelines/tools/podman.post-install.steps.yaml
+++ b/.pipelines/tools/podman.post-install.steps.yaml
@@ -9,10 +9,12 @@ steps:
     
     ls -l
     mkdir -p /home/"$PODMAN_USER"/.config/containers
+    mkdir -p /home/"$PODMAN_USER"/.config/systemd/user/
+    mkdir -p /home/"$PODMAN_USER"/.local/share/containers/
     cp azure-container-networking/.pipelines/tools/podman-containers.conf /home/"$PODMAN_USER"/.config/containers/containers.config
     cp azure-container-networking/.pipelines/tools/storage.conf /home/"$PODMAN_USER"/.config/containers/storage.config
+    cp azure-container-networking/.pipelines/tools/test.service /home/"$PODMAN_USER"/.local/share/containers/
     
-    mkdir -p /home/"$PODMAN_USER"/.local/share/containers
     chown podman:podman -R /home/"$PODMAN_USER"
     # Assign ownership to user
     #chmod 644 /etc/containers/containers.conf
@@ -42,3 +44,27 @@ steps:
     # Allow Build Env to take advantage of variable exports
     echo >&2 "##vso[task.setvariable variable=_CONTAINERS_USERNS_CONFIGURED]"""
     echo >&2 "##vso[task.setvariable variable=BUILDAH_ISOLATION]chroot"
+
+    #- bash: |
+        #set -e
+        #ls -l /usr/share/containers/
+        ##sudo ls -l /etc/containers || echo "No folder named /etc/containers"
+        #BUILD_USER="$(whoami)"
+        #sudo groupadd podman
+        #usermod -aG podman "$BUILD_USER"
+        ##mkdir -p /home/"$BUILD_USER" /home/"$BUILD_USER"/.config/containers -p /home/"$BUILD_USER"/.local/share/containers
+        ##usermod -d /home/"$BUILD_USER" "$BUILD_USER"
+        #echo podman:10000:5000 > /etc/subuid
+        #echo podman:10000:5000 > /etc/subgid
+        ##echo -e "$BUILD_USER:1:999\n$BUILD_USER:1001:124535" > /etc/subuid
+        ##echo -e "$BUILD_USER:1:999\n$BUILD_USER:1001:124535" > /etc/subgid
+        ##
+        ##echo "${BUILD_USER}:x:$BUILD_USER_ID:0:${BUILD_USER} user:/home/$BUILD_USER:/bin/bash" >> /etc/passwd
+        ##echo "${BUILD_USER}:x:$BUILD_USER_ID:" >> /etc/group
+        ##chmod 644 /etc/containers/containers.conf && \
+        ##chmod 644 /etc/containers/storage.conf || echo "unable to update permissions."
+        #setcap cap_setuid+ep /usr/bin/newuidmap
+        #setcap cap_setgid+ep /usr/bin/newgidmap
+        ##chmod 555 /etc/passwd /etc/group /etc/subuid /etc/subgid /usr/bin/newgidmap
+        #podman system migrate
+      #displayName: "Set up Build User Permissions for Podman"
