fixup! Add Agent Details

diff --git a/.pipelines/run-pipeline.yaml b/.pipelines/run-pipeline.yaml
--- a/.pipelines/run-pipeline.yaml
+++ b/.pipelines/run-pipeline.yaml
@@ -14,6 +14,7 @@ stages:
     - checkout: azure-container-networking
 
     - bash: |
+        set -e
         pushd "$ACN_DIR"
           BUILD_NUMBER="${BUILD_BUILDNUMBER//./-}"
           COMMIT_ID=""$(make revision)"-"$(date "+%d%H%M")""
@@ -35,9 +36,9 @@ stages:
           echo >&2 "[endgroup]"
           echo "$PATH"
           echo "------"
-          echo "${BUILD_QUEUEDBY}
-          echo "${BUILD_REASON} # manual, PR, IndividualCI
-          echo "${BUILD_SOURCEBRANCH}
+          echo "${BUILD_QUEUEDBY}"
+          echo "${BUILD_REASON}" # manual, PR, IndividualCI
+          echo "${BUILD_SOURCEBRANCH}"
         popd
       name: "EnvironmentalVariables"
       displayName: "Set environmental variables"
@@ -96,35 +97,43 @@ stages:
 #        displayName: "Run Windows Tests"
 #
 #- ${{ else }}:
-#  - stage: test
-#    displayName: Test ACN
-#    dependsOn:
-#    - setup
-#    variables:
-#      ob_outputDirectory: "$(Build.ArtifactStagingDirectory)"
-#    jobs:
-#    - job: test
-#      displayName: Run Tests
-#      variables:
-#        STORAGE_ID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.StorageID'] ]
-#      pool:
-#        type: linux
-#      steps:
-#      - checkout: azure-container-networking
-#
-#      - script: |
-#          make tools
-#          # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml), stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code. Read all output from fd 4 (output from tee) and write to top stdout
-#          { { { {
-#                sudo -E env "PATH=$PATH" make test-all;
-#                echo $? >&3;
-#                } | tee >(build/tools/bin/go-junit-report > report.xml) >&4;
-#              } 3>&1;
-#            } | { read xs; exit $xs; }
-#          } 4>&1
-#        retryCountOnTaskFailure: 3
-#        name: "Test"
-#        displayName: "Run Tests"
+- stage: test
+  displayName: Test ACN
+  dependsOn:
+  - setup
+  jobs:
+  - job: test
+    displayName: Unit Tests 
+    pool:
+      type: linux
+    strategy:
+      ubuntu:
+        suffix: ubuntu
+        LinuxContainerImage: "ubuntu:22.04"
+      mariner:
+        suffix: linux
+    variables:
+      STORAGE_ID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.StorageID'] ]
+      ob_outputDirectory: "$(Build.ArtifactStagingDirectory)"
+      ACN_DIR: $(Build.Repository.LocalPath)
+    steps:
+    - checkout: azure-container-networking
+
+    - bash: |
+        set -e
+        pushd "$ACN_DIR"
+          make tools
+          # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml), stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code. Read all output from fd 4 (output from tee) and write to top stdout
+          { { { {
+                sudo -E env "PATH=$PATH" make test-all;
+                echo $? >&3;
+                } | tee >(build/tools/bin/go-junit-report > report.xml) >&4;
+              } 3>&1;
+            } | { read xs; exit $xs; }
+          } 4>&1
+        popd
+      retryCountOnTaskFailure: 3
+      displayName: "Run Unit Tests (Ubuntu)"
 
 #  - stage: test_windows
 #    displayName: Test ACN Windows
